<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>fhir_distillery</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hl7.Fhir.Specification.Data.R4" Version="5.13.4" />
    <PackageReference Include="Hl7.Fhir.Specification.R4" Version="5.13.4" />
  </ItemGroup>


</Project>
