<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>fhir.distillery.test</RootNamespace>
    <UserSecretsId>33f1a79b-8e80-46ca-a738-80644dc988f2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hl7.Fhir.Specification.Data.R4" Version="5.13.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="OutputResources\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\fhir.distillery\fhir.distillery.csproj" />
  </ItemGroup>


</Project>
